name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      - name: Lint server
        run: npm run lint
        working-directory: ./server

      - name: Lint client
        run: npm run lint
        working-directory: ./client

      - name: Test server
        run: npm test
        working-directory: ./server

      - name: Build client
        run: npm run build
        working-directory: ./client

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Render
        run: |
          echo "Backend deployment triggered automatically by Render on push to main"
          
      - name: Deploy to Vercel
        run: |
          echo "Frontend deployment triggered automatically by Vercel on push to main" 