name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm ci

      - name: Install server dependencies
        run: npm ci
        working-directory: ./server

      - name: Install client dependencies
        run: npm ci
        working-directory: ./client

      - name: Lint server
        run: npm run lint || true
        working-directory: ./server

      - name: Lint client
        run: npm run lint || true
        working-directory: ./client

      - name: Test server
        run: npm test
        working-directory: ./server

      # Add more steps as needed (build, test client, etc.) 